// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_k1plFfqero7yIVQqm9tYrd583V1wgQ',
    appId: '1:287404054826:web:6f266f0a339406c98ba653',
    messagingSenderId: '287404054826',
    projectId: 'ai-generation-d4f06',
    authDomain: 'ai-generation-d4f06.firebaseapp.com',
    storageBucket: 'ai-generation-d4f06.appspot.com',
    measurementId: 'G-FFBJKK1LFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-A1tRxPzhgWIQLj_AttU2B3Cz922witI',
    appId: '1:287404054826:android:def5508531f6e0d88ba653',
    messagingSenderId: '287404054826',
    projectId: 'ai-generation-d4f06',
    storageBucket: 'ai-generation-d4f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMRa4ib0L-Ttr5gTuAAmNiu3YYRN0Uqc',
    appId: '1:287404054826:ios:6e82969e0ea884a78ba653',
    messagingSenderId: '287404054826',
    projectId: 'ai-generation-d4f06',
    storageBucket: 'ai-generation-d4f06.appspot.com',
    iosClientId: '287404054826-fr6udsaufhjfmh04q97sldnp88o8fmhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.artImagesGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMRa4ib0L-Ttr5gTuAAmNiu3YYRN0Uqc',
    appId: '1:287404054826:ios:3777d0b53f4a8b438ba653',
    messagingSenderId: '287404054826',
    projectId: 'ai-generation-d4f06',
    storageBucket: 'ai-generation-d4f06.appspot.com',
    iosClientId: '287404054826-mjeov4vuhe90g9cci94i7v4tsk89fn07.apps.googleusercontent.com',
    iosBundleId: 'com.example.artImagesGenerator.RunnerTests',
  );
}
